config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'posts/index'
  root 'posts#index'
  resources :posts
  root to: "home#index"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  mount_uploader :file, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def fullName
    "#{firstName&.capitalize} #{lastName&.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:firstName, :lastName)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:firstName, :lastName, :email, :current_password, :password, :password_confirmation)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: [:show, :edit, :destroy, :update]
  before_action :logged_in_user_equal_to_currentuser, only: [:edit, :destroy, :update]
  before_action :logged_in_user, only: [:new]

  def authorized_attributes
    params
        .require(:post)
        .permit(:title, :file, :lead, :content, :user_id)
  end

  def create
    @post = Post.new authorized_attributes
    @post.user_id = current_user.id
    @post.date = Time.now
    puts @post.inspect
    puts current_user.inspect
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_index_path
  end

  def index
    @posts = Post.all.order('id desc').paginate(:page => params[:page], :per_page => 5)
  end

  def load_post
    @post = Post.find params[:id]
  end

  def logged_in_user
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def logged_in_user_equal_to_currentuser
    unless user_signed_in? && @post.user_id == current_user.id
      redirect_to new_user_session_path
    end
  end

  def new
    @post = Post.new
  end

  def update
    if @post.update(authorized_attributes)
      redirect_to @post
    else
      render "edit"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user
  def load_user
    @user = User.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-primary">
      <div class="navbar-brand">
        <%= link_to "Blog", root_path, :class => "navbar-item"%>
      </div>
      <div class="navbar-end">
        <% if user_signed_in? %>
          <div class="navbar-item">Logged in as <%= current_user.firstName %> <%= current_user.lastName %></div>
          <div class="navbar-item">
            <%= link_to 'Edit profile', edit_user_registration_path, :class => "button" %>
          </div>
          <div class="navbar-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "button is-danger"  %>
          </div>

        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => "navbar-item"  %>
          <%= link_to "Login", new_user_session_path, :class => "navbar-item"  %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br/>
  <%= f.label :lead %>
  <%= f.text_field :lead %><br/>
  <%= f.label :file %>
  <%= f.file_field :file %><br/>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit "Save" %>
  <%- if @post.new_record? %>
    <%= link_to "Back", :posts %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h2>Update</h2>
<%= render partial: "form" %>

app/views/posts/index.html.erb
<div class="container">
  <div style="margin: 1rem">
    <h1 class="title is-1 is spaced">View Posts</h1>
    <h2 class="subtitle">See the latest posts</h2>
  </div>
  <div style="margin: 1rem">
    <%- if current_user %>
      <%= link_to "Create a new post", new_post_path, class:"button is-primary is-outlined"%>
    <% end %>
  </div>

  <br/>

  <%= will_paginate @posts %>

  <%- @posts.each do |post| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <img src='<%= post.file.thumb %>' />
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= post.title %></strong> <small>by <%=post.user.fullName %></small> <small><%=post.created_at.strftime('%F %H:%M') %></small>
              <br>
              <%= post.lead %>
            </p>
          </div>
          <div>
            <%= link_to post_path(post) do %>See more... <% end %></div>
        </div>
      </article>
    </div>
  <%- end %>

</div>

app/views/posts/new.html.erb
<h2>Create</h2>
<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="post_image"><img src='<%= @post.file.large %>' /></div>

<div class="content">
  <div class="post_title">
    <h1 class="title is-1"><%= @post.title %></h1>
    <h2 class="subtitle"><%= @post.lead %></h2>
  </div>

  <div class="post_presentation">
    Post by <%= link_to @post.user.fullName, user_path(@post.user_id) %> at <%= @post.date %>
  </div>
  <div class="post_buttons">
    <%- if @post.user == current_user %>
      <%= link_to "Edit", edit_post_path(@post), class:"button is-primary is-outlined"%>
      <%= link_to "Delete", post_path(@post), method: :delete, class:"button is-danger is-outlined"%>
    <% end %>
    <%= link_to "Back", :posts, class:"button is-primary is-outlined"%>
  </div>
  <div class="post_content">
    <div class="box">
      <%= @post.content %>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="content">
  <h1 class="title is-1"><%= @user.firstName%> <%= @user.lastName %></h1>
  <p>Email : <%= @user.email %></p>
</div>